on: push

jobs:
   build_macos:
    strategy:
      matrix:
        architecture: ['x86_64', 'arm64']
    runs-on: macos-latest
    steps:
      # Need to download godot-cpp, compile it, and the steamworks sdk
           # Checkout current source of GodotSteam
      - name: Checkout GodotSteam
        uses: actions/checkout@v3
      - name: Install Build Tools
        run: |
          brew install scons yasm
      - name: Checkout godot-cpp
        run: git clone --recursive -b 3.5 https://github.com/godotengine/godot-cpp
      - name: Compile godot-cpp
        run: |
          cd godot-cpp
          scons platform=osx macos_arch=${{ matrix.architecture }} generate_bindings=yes target=release
          cd ..
      - name: Compile GodotSteam
        run: |
          scons platform=osx macos_arch=x64_64 production=yes target=release
      - name: Print compiled
        run: |
          ls -al
          ls -al bin/osx
    #  - name: Upload macOS dylib
     #   uses: actions/upload-artifact@v3
      #  with:
       #   name: macos-template-app
        #  path: godot/misc/dist/osx_template.zip
         # if-no-files-found: error
          #retention-days: 1