on: 
  push:
  workflow_call:
    inputs:
      steamworks_sdk_tag:
        required: true
        type: string
      godot_tag:
        required: true
        type: string
      version_tag:
        required: true
        type: string
      binary_name:
        required: true
        type: string
      artifact_name:
        required: true
        type: string
    secrets:
      steamworks_sdk_repo:
        required: true
      steamworks_sdk_repo_token:
        required: true

jobs:
  build-macos:
    runs-on: macos-latest
    steps:
      # Need to download godot-cpp, compile it, and the steamworks sdk
           # Checkout current source of GodotSteam
      - name: Checkout GodotSteam
        uses: actions/checkout@v3
      - name: Install Build Tools
        run: |
          brew install scons yasm
      - name: Checkout godot-cpp
        run: git clone --recursive -b 3.5 https://github.com/godotengine/godot-cpp
      - name: Compile godot-cpp
        run: |
          cd godot-cpp
          scons platform=osx macos_arch=x86_64 generate_bindings=yes target=release
          cd ..